var kivaSupportedCountriesDict ={ 
     AL:["albania"], 
     AM:["armenia"],
     AZ:["azerbaijan"],
     BI:["burundi"],
     BJ:["benin"],
     BO:["bolivia"],
     CD:["congo"],
     CO:["colombia"],
     CR:["costa rica"],
     DO:["dominican republic"],
     EC:["ecuador"],
     GH:["ghana"],
     GT:["guatemala"],
     HN:["honduras"],
     ID:["indonesia"],
     IL:["isreal"],
     IN:["india"],
     IQ:["iraq"],
     JO:["jordan"],
     KE:["kenya"],
     KG:["kyrgyzstan"],
     KH:["cambodia"],
     LB:["lebanon"],
     LR:["liberia"],
     ML:["mali"],
     MN:["mongolia"],
     MX:["mexico"],
     MZ:["mozambique"],
     NG:["nigeria"],
     NI:["nicaragua"],
     PE:["peru"],
     PH:["philippines"],
     PK:["pakistan"],
     PS:["palestine"],
     PY:["paraguay"],
     RW:["rwanda"],
     SL:["sierra leone"],
     SN:["senegal"],
     SV:["el salvador"],
     TG:["togo"],
     TJ:["tajikistan"],
     TL:["timor-liste"],
     TZ:["tanzania"],
     UA:["ukraine"],
     UG:["uganda"],
     US:["united states"],
     VN:["vietnam"],
     WS:["samoa"],
     YE:["yemen"],
     ZM:["zambia"],
     ZW:["zimbabwe"]
};

exports.kivaSupportedCountries = kivaSupportedCountriesDict;