var cache     = require('memory-cache');
var tasks     = require('./taskScheduler.js');
var common    = require('./common.js');
var router    = require('./apirouter.js');
var dbControl = require('./dbcontrol.js')

//start the database, on completion start the startup tasks
var dbSetup = Object.create(dbControl.DatabaseSetup);

dbSetup.configureDatabase(function(database){
  //on completion of the startup tasks, start the API
  tasks.scheduleTasks(cache,database,function(){
    var apiRouter = Object.create(router.Api);
    apiRouter.beginListening(cache,database);
  });
});

var kivaString = 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n' 
+ 'MM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMMM.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMMMM  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMMMMM .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMMMMM$  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMMMMMM  .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMMMMMMZ  DMMMMMMMMMMMMMMMM. MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.  DMMMMMMMM' + '\n'
+ 'MMMMMMMMM   MMMMMMMMMM. .    DMMMMMM  ,MMM   MMMMMMMMMMMM   MMMMM          MMMMM' + '\n'
+ 'MMMMMMMMM    MMMMMM         MMMMMMMM  ,MMM   MMMMMMMMMMM.  MMMM.  ,MMMMM?   MMMM' + '\n'
+ 'MMMMMMMMMM   MMMMM.        MMMMMMMMM  ,MMMM  .MMMMMMMMMM  +MMMZ  7MMMMMMMM.  MMM' + '\n'
+ 'MMMMMMMMMM.  .MMM.      ,MMMMMMMMMMM  ,MMMMZ  NMMMMMMMM. .MMMM   MMMMMMMMMD  MMM' + '\n'
+ 'MMMMMMMMMM.   MMM .   MMMMMMMMMMMMMM  ,MMMMM   MMMMMMMM  MMMMM  .MMMMMMMMMM  MMM' + '\n'
+ 'MMMMMMMMMM$   .~?MMMMMMMMMMMMMMMMMMM  ,MMMMMM  NMMMMMM.  MMMMM  .MMMMMMMMMM  MMM' + '\n'
+ 'MMMMMMMMMMM    .MMMMMMMMMMMMMMMMMMMM  ,MMMMMM   MMMMM=  MMMMMM   MMMMMMMMMM  MMM' + '\n'
+ 'MMMMMMMMMMM    +M.DMMMMMMMMMMMMMMMMM  ,MMMMMMM  :MMMM   MMMMMM               MMM' + '\n'
+ 'MMMMMMMMMMM     MM       MMMMMMMMMMM  ,MMMMMMM.  MMM   MMMMMMM  .MMMMMMMMMM  MMM' + '\n'
+ 'MMMMMMMMMMM.    MM          MMMMMMMM  ,MMMMMMMM.  MM  OMMMMMMM  .MMMMMMMMMM  MMM' + '\n'
+ 'MMMMMMMMMMM     MMM          .MMMMMM  ,MMMMMMMMM  M  .MMMMMMMM  .MMMMMMMMMM  MMM' + '\n'
+ 'MMMMMMMMMMM     8MMM           IMMMM  ,MMMMMMMMM    .MMMMMMMMM  .MMMMMMMMMM  MMM' + '\n'
+ 'MMMMMMMMMMM.    .MMMMD          .MMM  ,MMMMMMMMMM   .MMMMMMMMM  .MMMMMMMMMM  MMM' + '\n'
+ 'MMMMMMMMMMMMMMMMMMMMMMMMM, ...   MMMZZ8MMMMMMMMMMZZZMMMMMMMMMM$$$MMMMMMMMMM$$MMM' + '\n'
+ 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' + '\n'
+ 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM';

console.log(kivaString);

//log uncaught exception for debug
process.on('uncaughtException', function (err) {
  console.log(err);
})
